name: "Code Review"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sast:
    name: Security Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initialises the CodeQL tools for scanning (sorry Americans)
    - name: Initialise CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  semgrep:
    name: Docker Lint
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run semgrep
        run: semgrep ci --sarif --output=semgrep-results.sarif
        env:
          SEMGREP_RULES: p/dockerfile

      - name: Upload output
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep-results.sarif
